[package]
name = "jam_whitelist_authorizer"
version = "0.1.0"
edition = "2021"

[dependencies]
jam-types = "0.1.12"         # Suggested version in the documentation
jam-pvm-builder = "0.1.12"   # Suggested version in the documentation
serde = "1.0.218"