[package]
name = "jam_whitelist_authorizer"
version = "0.1.0"
edition = "2021"

[dependencies]
jam-types = "0.1.12"         # Versi贸n sugerida en la documentaci贸n
jam-pvm-builder = "0.1.12"   # Versi贸n sugerida en la documentaci贸n
serde = "1.0.218"